import Head from 'next/head'
import { useEffect, useState } from 'react'
import Balloon from '../components/Balloon'
import Game from '../components/Game'

const allowedTafels = [1, 2, 3, 4, 5, 6, 7, 8, 9]

function generateQuestion()
{
  const q1 = allowedTafels[Math.floor(Math.random() * allowedTafels.length)];
  const q2 = allowedTafels[Math.floor(Math.random() * allowedTafels.length)];
  return {q1: q1, q2: q2, type: 'mul'}
}

export default function Home() {
  const [question, setQuestion] = useState({q1: null, q2: null, type: 'mul' })
  
  useEffect(() => {
    setQuestion(generateQuestion())
  }
  ,[])

  return (<>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <p className='absolute text-white font-semibold text-2xl ml-2 mb-2 left-0 bottom-0'>Score: 0</p>
    <div className='min-h-screen h-full bg-[#0033ff] w-full'>
      <Game question={question} />
    </div>
  </>




  )
}
